name: learn-github-actions
on: [pull_request]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        env:
          title2: ${{ github.event.pull_request.title }}
        run: |
          title="$title2"
          if [[ $title =~ ^FEATURE ]]; then
          echo "PR title starts with 'FEATURE'"
          exit 0
          else
          echo "PR title did not start with 'FEATURE'"
          exit 1
          fi
